# general settings
name: ESRGAN_x1_qf_10_r1_penalty_stochastic_faithful_500_FFHQ
model_type: ESRGANModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: FFHQ
    type: JPEGDataset
    dataroot_gt: /home/sean.man/datasets/ffhq_128/train/dummy
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 128
    use_hflip: true
    use_rot: false
    qf: 10

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 10
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: FFHQ
    type: JPEGDataset
    dataroot_gt: /home/sean.man/datasets/ffhq_128/val/dummy
    io_backend:
      type: disk
    qf: 10

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  scale: 1
  noise_injection: true

network_d:
  type: ResNetGANStabilityDiscriminator
  size: 128

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  r1_penalty_coef: 1.0
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0., 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0., 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 200000, 300000, 350000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: JPEGFaithfulnessLoss
    loss_weight: 500.0
    loss_type: 'mse'
    reduction: mean
  gan_opt:
    type: GANLoss
    gan_type: wgan_softplus
    loss_weight: 1.0

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true
  save_lq_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    faithfulness_rmse:
      type: calculate_jpeg_faithfulness_rmse
      crop_border: 0
      qf: 10
      test_y_channel: false
      better: lower  # the lower, the better
    fid:
      type: calculate_fid_given_paths
      gt_path: /home/sean.man/datasets/ffhq_128/train/dummy
      dims: 2048
      num_workers: 10
      batch_size: 64
      better: lower  # the lower, the better

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: jpeg
    group: ffhq128_stochastic
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
