###########
# start from pretrained G/D networks (ESRGAN_x1_qf_5_nf64_r1_stochastic_first_moment_bs16_1e-1_faithful_1e-1_1e1_0.5_1_0.1_FFHQ128) at step 255,000.
# adjust LR, LR scheduler, Consistency scheduler, Iterations accordingly (start from 3e-5, 3e-5:1e-7@200,000, 7e0:1e1, 200,000 respectively).
###########

# general settings
name: ESRGAN_x1_qf_5_nf64_r1_stochastic_first_moment_bs16_1e-1_faithful_7e0_1e1_0.5_1_0.1_var_1e-1_FFHQ128
model_type: ESRGANModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: FFHQ
    type: JPEGDataset
    dataroot_gt: /home/sean.man/datasets/ffhq_128/train/dummy
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 128
    use_hflip: true
    use_rot: false
    qf: 5

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 10
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: FFHQ
    type: JPEGDataset
    dataroot_gt: /home/sean.man/datasets/ffhq_128/val/dummy
    io_backend:
      type: disk
    qf: 5

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  scale: 1
  noise_injection: true
  noise_injection_upsample: true

network_d:
  type: ResNetGANStabilityDiscriminator
  size: 128
  nfilter: 64

# path
path:
  pretrain_network_g: /home/sean.man/faithful-jpeg-decoding/experiments/ESRGAN_x1_qf_5_nf64_r1_stochastic_first_moment_bs16_1e-1_faithful_1e-1_1e1_0.5_1_0.1_FFHQ128/models/net_g_255000.pth
  pretrain_network_d: /home/sean.man/faithful-jpeg-decoding/experiments/ESRGAN_x1_qf_5_nf64_r1_stochastic_first_moment_bs16_1e-1_faithful_1e-1_1e1_0.5_1_0.1_FFHQ128/models/net_d_255000.pth
  strict_load_g: true
  strict_load_d: true
  resume_state: ~ #/home/sean.man/faithful-jpeg-decoding/experiments/ESRGAN_x1_qf_5_nf64_r1_stochastic_first_moment_bs16_1e-1_faithful_1e-1_1e1_0.5_1_0.1_FFHQ128/training_states/255000.state

# training settings
train:
  r1_penalty_coef: 1.0
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 3e-5
    weight_decay: 0
    betas: [0., 0.99]
  optim_d:
    type: Adam
    lr: !!float 3e-5
    weight_decay: 0
    betas: [0., 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [ 200000 ]
    restart_weights: [ 1 ]
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: DCTFaithfulnessLoss
    loss_weight: !!float 7e0
    thr: 0.5
    pow: 1.0
    margin: 0.1
    annealing_opt:
      max: !!float 1e1
      min: !!float 7e0
      direction: up
  stability_opt:
    type: FirstMomentLoss
    loss_weight: !!float 1e-1
    reduction: mean
    batch_size: 8
    expansion: 16
    iters: 8
  variability_opt:
    type: MaxSTDLoss
    loss_weight: !!float 1e-1
    reduction: mean
  gan_opt:
    type: GANLoss
    gan_type: wgan_softplus
    loss_weight: !!float 1e-3

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false #true
  save_lq_img: false #true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    faithfulness_rmse:
      type: calculate_jpeg_faithfulness_rmse
      crop_border: 0
      qf: 5
      test_y_channel: false
      better: lower  # the lower, the better
    fid:
      type: calculate_fid_given_paths
      gt_path: /home/sean.man/datasets/ffhq_128/train_fid_stats.npz
      dims: 2048
      num_workers: 10
      batch_size: 64
      better: lower  # the lower, the better

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: jpeg
    group: ffhq128_var_loss
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
